name: Get Followers

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  filename: metrics.plugin.people.followers.svg
                  token: ${{ secrets.METRIC_TOKEN }}
                  base: ''
                  plugin_people: yes
                  plugin_people_identicons_hide: yes
                  plugin_people_types: followers
                  config_timezone: Asia/Kolkata
