name: Followers Metrics

on:
    schedule:
        - cron: '0 */24 * * *' # ‚è∞ Updates every 24 hours
    workflow_dispatch:
    push:
        branches:
            - '**'
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  filename: metrics.plugin.people.followers.svg
                  token: ${{ secrets.METRIC_TOKEN }} # üîê Use your classic token secret
                  base: ''
                  plugin_people: yes
                  plugin_people_identicons_hide: yes
                  plugin_people_types: followers
                  config_timezone: Asia/Kolkata
