name: github-stats
on:
    workflow_dispatch:
    schedule:
        - cron: '30 0 * * *'
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRIC_TOKEN }}

                  user: raj8664
                  template: classic
                  base: header, activity, community, repositories, metadata
                  base_indepth: yes
                  config_timezone: Asia/Kolkata
<<<<<<< Updated upstream
                  plugin_activity: yes
                  plugin_activity_days: 14
                  plugin_activity_filter: all
                  plugin_activity_limit: 5
                  plugin_activity_load: 300
                  plugin_activity_visibility: all
                  plugin_habits: yes
                  plugin_habits_charts: yes
                  plugin_habits_charts_type: classic
                  plugin_habits_days: 14
                  plugin_habits_facts: yes
                  plugin_habits_from: 200
                  plugin_habits_languages_limit: 5
                  plugin_habits_languages_threshold: 0%
                  plugin_languages: yes
=======
                  plugin_languages: no
>>>>>>> Stashed changes
                  plugin_languages_analysis_timeout: 60
                  plugin_languages_analysis_timeout_repositories: 20
                  plugin_languages_categories: markup, programming
                  plugin_languages_colors: github
                  plugin_languages_details: percentage, lines, bytes-size
                  plugin_languages_indepth: yes
                  plugin_languages_limit: 5
                  plugin_languages_recent_categories: markup, programming
                  plugin_languages_recent_days: 60
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%
                  plugin_lines: yes
                  plugin_lines_history_limit: 10
                  plugin_lines_repositories_limit: 3
                  plugin_lines_sections: repositories
                  repositories_forks: yes
