name: Metrics
on:
    schedule: [{ cron: '0 * * * *' }]
    workflow_dispatch:
    push: { branches: ['master', 'main'] }
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: lowlighter/metrics@latest
              with:
                  token: ${{ secrets.METRIC_TOKEN }}
                  user: github-profile
                  template: classic
                  base: header, activity, community, repositories, metadata
                  base_indepth: yes
                  config_timezone: Asia/Kolkata
                  plugin_languages: yes
                  plugin_languages_analysis_timeout: 5
                  plugin_languages_analysis_timeout_repositories: 7.5
                  plugin_languages_colors: github
                  plugin_languages_limit: 15
                  plugin_languages_recent_days: 14
                  plugin_languages_recent_load: 300
                  plugin_languages_sections: most-used
                  plugin_languages_threshold: 0%
                  plugin_lines: yes
                  plugin_lines_history_limit: 10
                  plugin_lines_repositories_limit: 15
                  plugin_lines_sections: base
